---
- block:
  - asb_last_operation:
      description: '{{ message }}'

  - lineinfile:
      line: '{{ message }}'
      path: '{{ crc_term_msg_filepath }}'
      unsafe_writes: true

  - fail:
      msg: "{{ message }}"
    when: result.failed

  when: result is defined